log_dir: "logs/access_logs"
monitor_log_dir: "logs/monitoring_logs"
login_fail_limit: 5
login_fail_window: 60
mask_user: true
allowed_countries:
  - BRAZIL
  - UNITED STATES
  - USA
  - RUSSIAN FEDERATION
  - CHINA
  - GERMANY
  - INDIA